module ActionCable
  module SubscriptionAdapter
    # == Test adapter for Action Cable
    #
    # The test adapter should be used only in testing. Along with
    # <tt>ActionCable::TestHelper</tt> it makes a great tool to test your Rails application.
    #
    # To use the test adapter set +adapter+ value to +test+ in your +config/cable.yml+ file.
    #
    # NOTE: Test adapter extends the <tt>ActionCable::SubscriptionsAdapter::Async</tt> adapter,
    # so it could be used in system tests too.
    class Test < Async
      def broadcast: (untyped channel, untyped payload) -> untyped

      def broadcasts: (untyped channel) -> untyped

      def clear_messages: (untyped channel) -> untyped

      def clear: () -> untyped

      private

      def channels_data: () -> untyped
    end
  end
end
