---
name: actionpack
version: '6.0'
source:
  type: git
  name: ruby/gem_rbs_collection
  revision: 64122cd55271ab8289dfb259e3aa157c26275bae
  remote: https://github.com/ruby/gem_rbs_collection.git
  repo_dir: gems
