default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: botti_now_development

test:
  <<: *default
  database: botti_now_test

production:
  <<: *default
  database: botti_now_production
