module ActionCable
  module Server
    # An instance of this configuration object is available via ActionCable.server.config, which allows you to tweak Action Cable configuration
    # in a Rails config initializer.
    class Configuration
      attr_accessor logger: untyped

      attr_accessor log_tags: untyped

      attr_accessor connection_class: untyped

      attr_accessor worker_pool_size: untyped

      attr_accessor disable_request_forgery_protection: untyped

      attr_accessor allowed_request_origins: untyped

      attr_accessor allow_same_origin_as_host: untyped

      attr_accessor cable: untyped

      attr_accessor url: untyped

      attr_accessor mount_path: untyped

      attr_accessor precompile_assets: untyped

      def initialize: () -> void

      # Returns constant of subscription adapter specified in config/cable.yml.
      # If the adapter cannot be found, this will default to the Redis adapter.
      # Also makes sure proper dependencies are required.
      def pubsub_adapter: () -> untyped
    end
  end
end
