module ActionCable
  module Connection
    class Subscriptions
      # Collection class for all the channel subscriptions established on a given connection. Responsible for routing incoming commands that arrive on
      # the connection to the proper channel.
      # :nodoc:
      def initialize: (untyped connection) -> void

      def execute_command: (untyped data) -> untyped

      def add: (untyped data) -> (nil | untyped)

      def remove: (untyped data) -> untyped

      def remove_subscription: (untyped subscription) -> untyped

      def perform_action: (untyped data) -> untyped

      def identifiers: () -> untyped

      def unsubscribe_from_all: () -> untyped

      private

      attr_reader connection: untyped

      attr_reader subscriptions: untyped

      def find: (untyped data) -> untyped
    end
  end
end
