module ActionCable
  module Connection
    # Allows the use of per-connection tags against the server logger. This wouldn't work using the traditional
    # <tt>ActiveSupport::TaggedLogging</tt> enhanced Rails.logger, as that logger will reset the tags between requests.
    # The connection is long-lived, so it needs its own set of tags for its independent duration.
    class TaggedLoggerProxy
      attr_reader tags: untyped

      def initialize: (untyped logger, tags: untyped tags) -> void

      def add_tags: (*untyped tags) -> untyped

      def tag: (untyped logger) { () -> untyped } -> untyped

      private

      def log: (untyped `type`, untyped message) -> untyped
    end
  end
end
